# @package _global_

motion_manager:
  reset_track:
    steps_min: 10
    steps_max: 600
    grace_period: 5

# Globally accessible parameters
eval_overrides:
  motion_manager:
    reset_track:
      steps_min: 1000000
      steps_max: 1000001
