# @package _global_

agent:
  config:
    # Setup basic actor-critic structure
    model:
      config:
        actor:
          _target_: protomotions.agents.ppo.model.PPOActor
          _recursive_: False
          num_out: ${robot.number_of_actions}
          config:
            actor_logstd: -2.9
            mu_model:
              _target_: protomotions.agents.common.mlp.MultiHeadedMLP
              _recursive_: False
              config:
                num_out: ${robot.number_of_actions}
                input_models:
                  self_obs:
                    _target_: protomotions.agents.common.common.Flatten
                    _recursive_: False
                    num_in: ${robot.self_obs_size}
                    num_out: ${.num_in}
                    config:
                      obs_key: self_obs
                      normalize_obs: True
                      norm_clamp_value: 5
                trunk:
                  _target_: protomotions.agents.common.mlp.MLP
                  _recursive_: False
                  num_out: ${robot.number_of_actions}
                  config:
                    layers:
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false

        actor_optimizer:
          _target_: torch.optim.Adam
          lr: 2e-5
