# @package _global_

agent:
  config:
    modules:
      mlp_terrain:
        _target_: protomotions.agents.common.common.Flatten
        num_in: ${terrain.config.terrain_obs_num_samples}
        num_out: ${.num_in}
        config:
          obs_key: terrain
          normalize_obs: True
          norm_clamp_value: 5

    model:
      config:
        critic:
          config:
            input_models:
              terrain: ${agent.config.modules.mlp_terrain}

    extra_inputs:
      terrain: true  # we create as a dict to ensure hydra combines with other extra_inputs
