# @package _global_

agent:
  config:
    modules:
      transformer_terrain:
        _target_: protomotions.agents.common.mlp.MLP_WithNorm
        num_in: ${terrain.config.terrain_obs_num_samples}
        num_out: ${agent.config.model.config.actor.config.mu_model.config.transformer_token_size}
        config:
          normalize_obs: true
          norm_clamp_value: 5
          obs_key: terrain
          layers:
            - units: 256
              activation: relu
              use_layer_norm: false
            - units: 256
              activation: relu
              use_layer_norm: false

    # Setup basic actor-critic structure
    model:
      config:
        actor:
          config:
            mu_model:
              config:
                input_models:
                  terrain: ${agent.config.modules.transformer_terrain}

    extra_inputs:
      terrain: true  # we create as a dict to ensure hydra combines with other extra_inputs
