# @package _global_

defaults:
  - /agent/masked_mimic/agent
  - /env/mimic

  - /agent/masked_mimic/models/encoder
  - /agent/masked_mimic/models/prior
  - /agent/masked_mimic/models/text_conditioning
  - /agent/mimic/options/global_tracking
  - /agent/mimic/options/early_termination_tracking_err
  # To enable historical_self_obs_with_actions, uncomment the following line:
  - /agent/mimic/models/transformer_actor_historical_self_obs_with_actions

env:
  config:
    mimic_target_pose:
      enabled: true
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 4
    masked_mimic:
      enabled: true
    humanoid_obs:
      num_historical_steps: 4
