# @package _global_

defaults:
  - /agent/masked_mimic/agent_no_vae
  - /env/mimic

  - /agent/masked_mimic/models_no_vae/encoder
  - /agent/mimic/options/global_tracking
  - /agent/mimic/options/early_termination_tracking_err
  # To enable historical_self_obs_with_actions, uncomment the following line:
  - /agent/mimic/models/transformer_actor_historical_self_obs_with_actions
  
  # Constraint configurations - uncomment one of the following:
  - /opt/masked_mimic/constraints/g1_body
  - /opt/masked_mimic/constraints/near_future_only
  # - /opt/masked_mimic/constraints/far_future_only
  # - /opt/masked_mimic/constraints/text_only
  # - /opt/masked_mimic/constraints/mixed_training
env:
  config:
    mimic_target_pose:
      enabled: true
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 4
    masked_mimic:
      enabled: true
    humanoid_obs:
      num_historical_steps: 120
