# @package _global_

defaults:
  - /agent/masked_mimic/agent_no_vae
  - /env/mimic

  - /agent/masked_mimic/models_no_vae/encoder
  - /agent/masked_mimic/models_no_vae/text_conditioning
  - /terrain/complex
  - /agent/masked_mimic/models/terrain
  - /agent/mimic/options/global_tracking
  - /agent/mimic/options/early_termination_tracking_err
  - /agent/mimic/models/transformer_actor_historical_self_obs_with_actions
  - /opt/masked_mimic/constraints/g1_body
  
  # 训练模式选择 - 手动注释控制
  # 选择以下四种模式之一：
  
  # 1. 只训练远未来帧（类似no_constraint）
  # - /opt/masked_mimic/constraints/far_future_only
  
  # 2. 只训练近未来帧，所有keybody可见
  # - /opt/masked_mimic/constraints/near_future_only
  
  # 3. 只有文字embedding，没有远未来和近未来
  # - /opt/masked_mimic/constraints/text_only
  
  # 4. 混合训练（原来的g1_mocap_key_bodies）
  - /opt/masked_mimic/constraints/mixed_training

env:
  config:
    mimic_target_pose:
      enabled: true
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 4
    masked_mimic:
      enabled: true
      masked_mimic_target_pose:
        num_future_steps: 4
      historical_obs:
        num_historical_conditioned_steps: 4
    humanoid_obs:
      num_historical_steps: 4
