# @package _global_

agent:
  config:
    modules:
      mlp_mimic_phase:
        _target_: protomotions.agents.common.common.Flatten
        _recursive_: False
        num_in: 2
        num_out: ${.num_in}
        config:
          obs_key: mimic_phase
          normalize_obs: True
          norm_clamp_value: 5

    model:
      config:
        critic:
          config:
            input_models:
              mimic_phase: ${agent.config.modules.mlp_mimic_phase}

    extra_inputs:
      mimic_phase: true  # we create as a dict to ensure hydra combines with other extra_inputs

env:
  config:
    mimic_phase_obs:
      enabled: True
