# @package _global_

agent:
  config:
    modules:
      transformer_mimic_target_pose_model:
        _target_: protomotions.agents.common.mlp.MLP_WithNorm
        _recursive_: False
        num_in: ${env.config.mimic_target_pose.num_obs_per_target_pose}
        num_out: ${agent.config.model.config.actor.config.mu_model.config.transformer_token_size}
        config:
          obs_key: mimic_target_poses
          normalize_obs: true
          norm_clamp_value: 5

          operations:
            - type: reshape
              new_shape:
                - -1
                - ${env.config.mimic_target_pose.num_obs_per_target_pose}
            - type: encode
            - type: reshape
              new_shape:
                - batch_size
                - ${env.config.mimic_target_pose.num_future_steps}
                - ${agent.config.modules.transformer_mimic_target_pose_model.num_out}
          layers:
            - units: 256
              activation: relu
              use_layer_norm: false
            - units: 256
              activation: relu
              use_layer_norm: false

    model:
      config:
        actor:
          config:
            mu_model:
              config:
                input_models:
                  mimic_target_poses: ${agent.config.modules.transformer_mimic_target_pose_model}

    extra_inputs:
      mimic_target_poses: true

env:
  config:
    mimic_target_pose:
      enabled: True
      with_time: True
