# @package _global_

defaults:
  - /agent/amp/agent
  - /env/base_env

  - /agent/ppo/models/mlp_actor
  - /agent/ppo/models/mlp_critic
  - /agent/amp/models/mlp_discriminator

env:
  config:
    state_init: Data
    humanoid_obs:
      num_historical_steps: 8
