# @package _global_

defaults:
  - /agent/ase/agent
  - /env/base_env

  - /agent/ppo/models/mlp_actor
  - /agent/ppo/models/mlp_critic
  - /agent/ase/models/mlp_joint_discriminator_and_encoder
  - /agent/ase/models/mlp_actor_latent

env:
  config:
    enable_height_termination: True
    state_init: Data
    humanoid_obs:
      num_historical_steps: 8
