# @package _global_

defaults:
  - ppo_mlp
  - /env/steering

agent:
  config:
    task_reward_w: 1.0

    modules:
      steering:
        _target_: protomotions.agents.common.common.Flatten
        num_in: ${env.config.steering_params.obs_size}
        num_out: ${.num_in}
        config:
          obs_key: steering
          normalize_obs: true
          norm_clamp_value: 5

    # Append the direction obs to the actor and critic inputs
    model:
      config: 
        actor:
          config:
            mu_model:
              config:
                input_models:
                  steering: ${agent.config.modules.steering}
        critic:
          config:
            input_models:
              steering: ${agent.config.modules.steering}

    extra_inputs:
      steering: true
