# @package _global_

agent: ???

env: ???

robot: ???
simulator: ???

motion_lib: ???  # This is defined in the robot configs
# This is provided by the user.
# Can be null if reset using default pose and task doesn't use reference motions.
motion_file: null

terrain: ???  # This is defined in the terrain configs
