# @package _global_

env:
  config:
    masked_mimic:
      masked_mimic_masking:
        joint_masking:
          masked_mimic_fixed_conditioning:
            - body_name: Head
              constraint_state: 1

          time_gap_mask_min_steps: -2
          time_gap_mask_max_steps: -1

          masked_mimic_time_gap_probability: 0
          masked_mimic_repeat_mask_probability: 1

        target_pose_visible_prob: 0
        motion_text_embeddings_visible_prob: 0