# @package _global_

simulator:
  _target_: ???
  _config_target_: ???
  _recursive_: False
  config:
    w_last: ???  # IsaacGym is xyzw quaternions
    headless: ${headless}
    robot: ${robot}
    num_envs: ${num_envs}
    plane:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    sim:
      fps: ???
      decimation: ???

    camera: null

    record_viewer: False
    viewer_record_dir: "output/recordings/viewer"
    experiment_name: ${experiment_name}
