# @package _global_
defaults:
  - physx_interactions

simulator:
  config:
    sim:
      physx:
        gpu_found_lost_pairs_capacity: ${eval:2**22}
        gpu_max_rigid_contact_count: ${eval:2**24}
        gpu_found_lost_aggregate_pairs_capacity: ${eval:2**26}
