# @package _global_

agent:
  config:
    # Setup discriminator structure
    model:
      config:
        discriminator:
          _target_: protomotions.agents.amp.model.Discriminator
          _recursive_: False
          num_in: ${eval:${robot.self_obs_size}*${env.config.humanoid_obs.num_historical_steps}}
          num_out: 1
          config:
            obs_key: historical_self_obs
            normalize_obs: True
            norm_clamp_value: 5
            layers:
              - units: 1024
                activation: relu
                use_layer_norm: false
              - units: 512
                activation: relu
                use_layer_norm: false

        discriminator_optimizer:
          _target_: torch.optim.Adam
          lr: 1e-4

    extra_inputs:
      historical_self_obs: true  # we create as a dict to ensure hydra combines with other extra_inputs
