# @package _global_

defaults:
  - /agent/mimic/agent
  - /env/mimic

  - /agent/ppo/models/mlp_actor_large
  - /agent/ppo/models/mlp_critic_large
  - /agent/mimic/models/mlp_actor_target_pose
  - /agent/mimic/models/mlp_critic_target_pose
  - /agent/mimic/options/global_tracking
  - /agent/mimic/options/early_termination_tracking_err
  # To enable historical_self_obs_with_actions (compatible with both MLP and Transformer), uncomment the following line:
  - /agent/mimic/models/transformer_actor_historical_self_obs_with_actions
env:
  config:
    humanoid_obs:
      num_historical_steps: 4
    mimic_target_pose:
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 4
