# @package _global_

defaults:
  - /agent/mimic/agent
  - /env/mimic

  - /agent/ppo/models/transformer_actor
  - /agent/ppo/models/mlp_critic_large
  - /agent/mimic/models/transformer_actor_target_pose
  - /agent/mimic/models/mlp_critic_target_pose
  - /agent/mimic/options/global_tracking
  - /agent/mimic/options/early_termination_tracking_err

env:
  config:
    mimic_target_pose:
      type: max-coords-future-rel
      with_time: true
      num_future_steps: 15
