# @package _global_

defaults:
  - /agent/amp/agent

agent:
  _target_: protomotions.agents.ase.agent.ASE
  _recursive_: False
  config:
    # Setup discriminator structure
    model:
      _target_: protomotions.agents.ase.model.ASEModel  # Override main model
    # ASE parameters
    ase_parameters:
      latent_dim: 64

      mi_reward_w: 0.5
      mi_hypersphere_reward_shift: True

      mi_enc_weight_decay: 0
      mi_enc_grad_penalty: 0

      diversity_tar: 1.
      diversity_bonus: 0.01

      latent_steps_min: 1
      latent_steps_max: 150
