# @package _global_

fabric:
  loggers:
    - _target_: lightning.fabric.loggers.TensorBoardLogger
      root_dir: ${save_dir}
    - _target_: lightning.pytorch.loggers.WandbLogger
      name: ${experiment_name}
      save_dir: ${save_dir}
      project: ${wandb.wandb_project}
      tags: ${wandb.wandb_tags}
      group: ${wandb.wandb_group}
      id: ${wandb.wandb_id}
      entity: ${wandb.wandb_entity}
      resume: ${wandb.wandb_resume}

wandb:
  wandb_project: physical_animation
  wandb_tags: null
  wandb_group: null
  wandb_id: null
  wandb_entity: null
  wandb_resume: allow
