# @package _global_

# Configuration for historical_self_obs_with_actions transformer model
# 
# This configuration file should be included in the experiment config's defaults list
# to enable historical_self_obs_with_actions functionality.
# 
# NOTE: This feature is ONLY supported for transformer-based actors, not for MLP actors or critics.
# 
# Usage:
# 1. In experiment config (e.g., transformer_flat_terrain.yaml), add this line to defaults:
#    - /agent/mimic/models/transformer_actor_historical_self_obs_with_actions
# 2. The enabled flag is automatically set to True when this config is included
# 
# To disable:
# 1. Comment out the line in experiment config's defaults list
# 2. The enabled flag will remain False in the base config

agent:
  config:
    modules:
      transformer_historical_self_obs_with_actions_model:
        _target_: mirage.agents.common.mlp.MLP_WithNorm
        _recursive_: False
        num_in: ${env.config.humanoid_obs.historical_self_obs_with_actions.num_obs_per_step}
        num_out: ${agent.config.model.config.actor.config.mu_model.config.transformer_token_size}
        config:
          obs_key: historical_self_obs_with_actions
          normalize_obs: true
          norm_clamp_value: 5

          operations:
            - type: reshape
              new_shape:
                - -1
                - ${env.config.humanoid_obs.historical_self_obs_with_actions.num_obs_per_step}
            - type: encode
            - type: reshape
              new_shape:
                - batch_size
                - -1
                - ${agent.config.modules.transformer_historical_self_obs_with_actions_model.num_out}
          layers:
            - units: 512
              activation: relu
              use_layer_norm: true
            - units: 512
              activation: relu
              use_layer_norm: true

    model:
      config:
        actor:
          config:
            mu_model:
              config:
                input_models:
                  historical_self_obs_with_actions: ${agent.config.modules.transformer_historical_self_obs_with_actions_model}

    extra_inputs:
      historical_self_obs_with_actions: true

env:
  config:
    humanoid_obs:
      historical_self_obs_with_actions:
        enabled: True
        max_num_historical_steps: 8
        with_time: True
        num_obs_per_step: ${eval:${robot.self_obs_size}+${robot.number_of_actions}+1*${.with_time}}

