# @package _global_

env:
  config:
    mimic_early_termination:
      - mimic_early_termination_key: max_joint_err
        mimic_early_termination_thresh: 0.4
        mimic_early_termination_thresh_on_flat: 0.4 #for DR
        less_than: False

# At evaluation, disable early termination
eval_overrides:
  env:
    config:
      mimic_early_termination: null
