# @package _global_

agent:
  config:
    modules:
      mlp_latent:
        _target_: protomotions.agents.common.common.Flatten
        num_in: ${agent.config.ase_parameters.latent_dim}
        num_out: ${.num_in}
        config:
          obs_key: latents
          normalize_obs: True
          norm_clamp_value: 5

    model:
      config:
        actor:
          config:
            mu_model:
              config:
                input_models:
                  latents: ${agent.config.modules.mlp_latent}
