# @package _global_

defaults:
  - /agent/ppo/agent

agent:
  _target_: protomotions.agents.mimic.agent.Mimic
  config:
    # Mimic parameters
    gradient_clip_val: 50.0
    clip_critic_loss: True
    eval_metric_keys: ["cartesian_err", "gt_err", "dv_rew", "kb_rew", "lr_rew", "rv_rew", "rav_rew", "gr_err", "gr_err_degrees"]
    eval_length: null
    eval_num_episodes: 1

    # Early termination
    training_early_termination:
      early_terminate_cart_err: null
      early_terminate_success_rate: null
