# @package _global_

defaults:
  - base

simulator:
  _target_: protomotions.simulator.genesis.simulator.GenesisSimulator
  _config_target_: protomotions.simulator.genesis.config.GenesisSimulatorConfig
  config:
    w_last: false  # Genesis is wxyz quaternions
    sim:
      fps: ${robot.sim.genesis.fps}
      decimation: ${robot.sim.genesis.decimation}
      substeps: ${robot.sim.genesis.substeps}
