# @package _global_

defaults:
  - base
  - physx
  - flex

simulator:
  _target_: protomotions.simulator.isaacgym.simulator.IsaacGymSimulator
  _config_target_: protomotions.simulator.isaacgym.config.IsaacGymSimulatorConfig
  config:
    w_last: true  # IsaacGym is xyzw quaternions
    sim:
      fps: ${robot.sim.isaacgym.fps}
      decimation: ${robot.sim.isaacgym.decimation}
      substeps: ${robot.sim.isaacgym.substeps}
