# @package _global_

defaults:
  - base
  - physx_isaaclab

simulator:
  _target_: protomotions.simulator.isaaclab.simulator.IsaacLabSimulator
  _config_target_: protomotions.simulator.isaaclab.config.IsaacLabSimulatorConfig
  config:
    w_last: false  # IsaacLab is xyzw quaternions
    sim:
      fps: ${robot.sim.isaaclab.fps}
      decimation: ${robot.sim.isaaclab.decimation}
