# @package _global_
defaults:
  - physx

simulator:
  config:
    sim:
      physx:
        gpu_found_lost_pairs_capacity: ${eval:2**21}
        gpu_max_rigid_contact_count: ${eval:2**23}
        gpu_found_lost_aggregate_pairs_capacity: ${eval:2**25}
