# @package _global_

agent:
  config:
    modules:
      mlp_vae_output_head:
        _target_: protomotions.agents.common.mlp.MLP
        _recursive_: False
        num_in: 512
        num_out: ${agent.config.vae.latent_dim}
        config:
          layers:
            - units: 256
              activation: relu
              use_layer_norm: false
            - units: 128
              activation: relu
              use_layer_norm: false
    # Setup basic actor-critic structure
    model:
      config:
        encoder:
          _target_: protomotions.agents.masked_mimic.model.VaeModule
          _recursive_: False
          config:
            trunk:
              _target_: protomotions.agents.common.mlp.MultiHeadedMLP
              _recursive_: False
              num_out: 512
              config:
                input_models:
                  self_obs:
                    _target_: protomotions.agents.common.common.Flatten
                    _recursive_: False
                    num_in: ${robot.self_obs_size}
                    num_out: ${.num_in}
                    config:
                      obs_key: self_obs
                      normalize_obs: True
                      norm_clamp_value: 5
                  mimic_target_poses:
                    _target_: protomotions.agents.common.common.Flatten
                    _recursive_: False
                    num_in: ${eval:${env.config.mimic_target_pose.num_future_steps}*${env.config.mimic_target_pose.num_obs_per_target_pose}}
                    num_out: ${.num_in}
                    config:
                      normalize_obs: True
                      norm_clamp_value: 5
                      obs_key: mimic_target_poses
                  masked_mimic_target_bodies_masks:
                    _target_: protomotions.agents.common.common.Flatten
                    config:
                      normalize_obs: False
                      obs_clamp_value: null
                      obs_key: masked_mimic_target_bodies_masks
                    num_in: ${eval:${eval:${len:${robot.trackable_bodies_subset}}+1}*2*${env.config.masked_mimic.masked_mimic_target_pose.num_future_steps}}
                    num_out: ${.num_in}

                trunk:
                  _target_: protomotions.agents.common.mlp.MLP
                  _recursive_: False
                  num_out: 512
                  config:
                    layers:
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false
                      - units: 1024
                        activation: relu
                        use_layer_norm: false

            mu_head: ${agent.config.modules.mlp_vae_output_head}
            logvar_head: ${agent.config.modules.mlp_vae_output_head}
